/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Answers {
  createdAt: Generated<Timestamp>;
  durationSec: number | null;
  endedAt: Timestamp | null;
  gradedAt: Timestamp | null;
  gradedBy: string | null;
  id: Generated<string>;
  notes: string | null;
  numericValue: number | null;
  pointsAwarded: number | null;
  questionId: string;
  roomMemberId: string;
  selectedIndex: number | null;
  selectedIndices: Json | null;
  sessionId: string;
  startedAt: Timestamp | null;
  textValue: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface Exams {
  attempts: Generated<number>;
  authorId: string;
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  durationMin: Generated<number>;
  id: Generated<string>;
  scheduledAt: Timestamp | null;
  shuffleMode: Generated<string>;
  status: Generated<string>;
  subjectId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
  visibility: Generated<string>;
}

export interface Questions {
  createdAt: Generated<Timestamp>;
  difficulty: Generated<string>;
  id: Generated<string>;
  payload: Generated<Json>;
  points: Generated<number>;
  position: number;
  text: Generated<string>;
  ticketId: string;
  timeSec: Generated<number>;
  type: string;
  updatedAt: Generated<Timestamp>;
}

export interface RoomMembers {
  assignedTicketId: string | null;
  groupName: string;
  id: Generated<string>;
  joinedAt: Generated<Timestamp>;
  lastSeenAt: Generated<Timestamp>;
  name: string;
  online: Generated<boolean>;
  sessionId: string;
  sessionTokenHash: string;
  studentNumber: string | null;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  endedAt: Timestamp | null;
  examId: string;
  id: Generated<string>;
  scheduledAt: Timestamp | null;
  startedAt: Timestamp | null;
  status: Generated<string>;
  teacherId: string;
  ticketId: string;
  ticketsPolicy: Generated<string>;
  updatedAt: Generated<Timestamp>;
}

export interface Subjects {
  code: string;
  color: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  sigil: string;
  status: Generated<string>;
  teacherId: string;
  updatedAt: Generated<Timestamp>;
}

export interface Tickets {
  authorId: string;
  createdAt: Generated<Timestamp>;
  examId: string;
  id: Generated<string>;
  position: Generated<number>;
  subjectId: string;
  title: string;
  updatedAt: Generated<Timestamp>;
}

export interface Users {
  createdAt: Generated<Timestamp>;
  department: string | null;
  email: string;
  id: Generated<string>;
  name: string;
  passwordHash: string;
  role: string;
  updatedAt: Generated<Timestamp>;
}

export interface DB {
  answers: Answers;
  exams: Exams;
  questions: Questions;
  roomMembers: RoomMembers;
  sessions: Sessions;
  subjects: Subjects;
  tickets: Tickets;
  users: Users;
}
